### ISSUE TITLE
Why did you delete all the files??

### ISSUE THREAD

**Issue by mindless2831** [ABOhiccups/GBI-Speedrunning-Fullscreen#1]
Hey, I don't mean to complain, but this is exactly what I need and you deleted all the files as I can see in the history! Why?? You went through all this trouble, and you can't leave them to help people and for internet posterity's sake? Can you please please upload them back??

**Comment by ABOhiccups** [comment]
The reason why I deleted all .dol+cli files. It's because...
1) It was uploaded by mistake.
2) Game Boy Interface do get new updates and I don't want people download old versions. I'm too lazy to keep them up-to-date. That's why I created "Copy and Rename Generator" to create .dol+cli files with latest version of GBI Speedrunning.

If you want to download .dol.cli files. You need a gbisr.dol file from official [Game Boy Interface](https://www.gc-forever.com/wiki/index.php?title=Game_Boy_Interface) release.

Go to [Releases](https://github.com/ABOhiccups/GBI-Speedrunning-Fullscreen/releases) page in this repository. Download "Copy and Rename Generator" for an Operating System you're using and follow the instructions.

.dol+cli files are not going anywhere. You just have to do an extra step.

You can request Extrems to release my preset files on his official release set.

**Comment by mindless2831** [comment]
Oh wow, I did not realize that's what that was. Thank you for the help and
quick response, you are awesome and an answer to over a week of research if
this goes the way you describe. Thank you.

**Comment by ABOhiccups** [comment]
You're welcome!
